
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: Pasd!@#$12xzA12
  host: localhost

development:
  <<: *default
  database: project2

test:
  <<: *default
  database: project2


production:
  <<: *default
  database: project2
